name: CI Tutorial

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - deploy

jobs:
  "run-data-tests":
    runs-on:
      - self-hosted
      - linux
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Install Dependencies
        run: npm install

      - name: Remove Existing Database
        run: npx ts-node remove_db.ts ${{ secrets.MONGODB_URL }}


      - name: Insert Sample Data
        run: npx ts-node insert_sample_db.ts ${{ secrets.MONGODB_URL }}
